### ISSUE TITLE
This course meant for EXPO only??

### ISSUE THREAD

**Issue by isaaclem** [HandlebarLabs/master-push-notifications-react-native#1]
After subscribed the course only then I found that this course on how to master push notifications is meant for an expo app? Which means we must rely on the EXPO SDK and it's not gonna work if my projects are ReactNativeCLI??

**Comment by spencercarli** [comment]
From the email I just sent you 😄 

> Hey Isaac,
> 
> Thanks for the email! Sorry about the confusion regarding the usage of Expo. The goal of the course is to teach you strategies to effectively use push notifications in your app. The usage of Expo is like my usage of Express on the server - merely an implementation detail.
> 
> I covered this a bit in the FAQ on the sales page but it's understandable if you missed that/were confused by it. If you'd like a refund and to be un-enrolled in the course I'd be happy to do so.
> 
> Also, here's a guide I put together showing how to install OneSignal in a "pure" react native app instead if you want to use that to follow along. There are dozens of push notification providers so I can't cover them all.
> 
> Looking forward to hearing back!
> 
> Best,
> Spencer
