### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by weitieda** [HandlebarLabs/master-push-notifications-react-native#2]
Hi Spencer,

I run into a situation like this, needs to destructuring Expo, otherwise gave me an error.
```
TypeError: Expo.isExpoPushToken is not a function
```

[
![image](https://user-images.githubusercontent.com/35972055/50542486-54f24000-0b8c-11e9-9521-7c82579d8283.png)
](url)

**Comment by spencercarli** [comment]
Until I can get this fixed the solution would either be

`const { Expo } = require("expo-server-sdk");`
or
`import Expo from "expo-server-sdk";`

This break was introduced in `expo-server-sdk` v3.
